[main]
font=JetBrainsMono Nerd Font:size=13
prompt="❯ "
# icons-enabled=no
lines=10
width=30
horizontal-pad=30
vertical-pad=16
inner-pad=10

[colors]
background=000000ee
text=888888ff
prompt=ffffffff
input=ffffffff
match=ffffffff
selection=ffffffff
selection-text=444444ff
selection-match=000000ff
border=ffffffff

[border]
width=2
radius=6
